FROM golang:latest
WORKDIR /go/src/github.com/aratasato/geing-server
ENV GO111MODULE=on
ADD . /go/src/github.com/aratasato/geing-server
CMD ["go", "run", "/go/src/github.com/aratasato/geing-server/main.go"]